Create Table TableNameTest (Column_Name_One Varchar2(10),
Column_Name_Two Timestamp(6),
Column_Name_Three Varchar2(200),
Column_Name_Four Varchar2(300),
Column_Name_Five Date,
Column_Name_Six Number(38,10),
Column_Name_Seven Number(38,10),
Column_Name_Eight Varchar2(1000),
Column_Name_Nine Varchar2(2000),
Column_Name_Ten Number(38,10));